import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrappers from "@/components/Wrappers/Wrappers";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, "overflow-x-hidden")}>
        <Wrappers>{children}</Wrappers>
      </body>
    </html>
  );
}
